MyPro/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('warcraft.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

warcraft/urls.py
from django.urls import path
from .views import *

app_name = 'warcraft'
urlpatterns = [
    path('', StartView.as_view(), name='start_pages'),
    path('about/', AboutView.as_view(), name='about_pages'),
    path('gallery/', GalleryView.as_view(), name='gallery_pages'),
    path('video/', VideoView.as_view(), name='video_pages'),
]

warcraft/models.py
from django.db import models

# Create your models here.

warcraft/views.py
from django.views.generic import TemplateView


class StartView(TemplateView):
    template_name = 'warcraft/start_page.html'


class AboutView(TemplateView):
    template_name = 'warcraft/about_page.html'


class GalleryView(TemplateView):
    template_name = 'warcraft/gallery_page.html'


class VideoView(TemplateView):
    template_name = 'warcraft/video_page.html'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <title>Warcraft 3 Reign Of Chaos</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<nav>
    <div>
        <a class="logo" href="{% url 'warcraft:start_pages' %}">Warcraft 3</a>
    </div>
    <input type="checkbox" id="click">
    <label for="click" class="menu-btn">
        <i class="fas fa-bars"></i>
    </label>
    <ul>
        <li><a href="{% url 'warcraft:start_pages' %}">Home</a></li>
        <li><a href="{% url 'warcraft:about_pages' %}">About</a></li>
        <li><a href="{% url 'warcraft:gallery_pages' %}">Gallery</a></li>
        <li><a href="{% url 'warcraft:video_pages' %}">Video</a></li>
    </ul>
</nav>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
        integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
{% block content %}

{% endblock %}
</body>
</html>

warcraft/templates/warcraft/about_page.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="container mt-5 pt-5">
        <div class="row align-items-center">
            <div class="col-md-5">
                <img src="{% static 'images/Warcraft3_orc_cover.jpg' %}" alt="Обложка Warcraft III: Reign of Chaos"
                     class="img-fluid mb-3" style="max-width: 80%;">
            </div>
            <div class="col-md-6">
                <h1>Warcraft III: Reign of Chaos</h1>
                <p><strong>Разработчик:</strong> Blizzard Entertainment Team 2</p>
                <p><strong>Издатели:</strong> Флаг США Blizzard Entertainment, Флаг ЕС Sierra Entertainment, Флаг России
                    СофтКлаб, Флаг Японии Capcom</p>
                <a href="https://sirus.one/" target="_blank" class="btn btn-primary">Официальный сайт</a>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-md-12">
                <h2>Описание</h2>
                <p>Warcraft III: Reign of Chaos (от англ. Warcraft — «военное ремесло», Reign of chaos — «господство
                    хаоса») — компьютерная игра в жанре стратегии в реальном времени с элементами RPG. Разработана и
                    выпущена в июле 2002 года компанией Blizzard Entertainment при поддержке Vivendi Universal.

                    Warcraft III была одной из наиболее ожидаемых игр: более 4,5 миллионов предварительных заказов и
                    более одного миллиона копий игры, проданных менее чем за месяц, сделало её самой быстро
                    распродаваемой ПК-игрой на тот момент[1][2]. Она была встречена множеством положительных рецензий, а
                    часть изданий отметили игру титулами «Лучшая игра года» и «Лучшая стратегия года». Также игра
                    получила высокие оценки у игроков[3][4][5]. В чарте еженедельных продаж от NPD Techworld игра
                    занимала первое место два месяца[6].

                    В отличие от предыдущих игр серии количество противоборствующих сторон увеличилось с двух до
                    четырёх: кроме уже известных Альянса и Орды появилась возможность играть за две новые расы — Нежить
                    и Ночных эльфов. Однако общий игровой процесс при этом не изменился — игроку всё так же нужно
                    добывать ресурсы, отстраивать и улучшать базы и нанимать войска, с целью уничтожить армию
                    противника. Нововведением стали герои — уникальные юниты, имеющие особые способности и способные
                    получать опыт при убийстве воинов противника.

                    Сюжетная кампания игры начинается спустя 12 лет после событий Warcraft II: Beyond the Dark Portal и
                    рассказывает о пришествии демонов в мир Азерота[7].

                    В комплекте с игрой поставляется редактор карт World Editor, благодаря которому в сети появилось
                    множество неофициальных карт, в которых игровой процесс может полностью отличаться от обычного.
                    Одной из популярнейших карт стала DotA: Allstars, также получили развитие множество других
                    модификаций, таких как Tower Defense, Hero Survival и др. Через год к игре было выпущено дополнение:
                    The Frozen Throne, которое также стало популярно у игроков и получило множество положительных
                    рецензий[8].

                    2 ноября 2018 года на выставке BlizzCon 2018 было анонсировано переиздание игры Warcraft III:
                    Reforged с обновленной графикой, перезаписанными роликами и звуком, и поддержкой 4К-разрешений. Игра
                    вышла 29 января 2020 года и получила смешанные отзывы от критиков и крайне отрицательные оценки от
                    игроков.
            </div>
            <div class="row mt-4">
                <div class="col-md-12">
                    <h2>Разработка и развитие игры</h2>
                    <p>
                        Blizzard анонсировала Warcraft III, тогда ещё без приставки Reign of Chaos, 2 сентября 1999 года
                        на
                        европейской
                        выставке European Computer Trade Show (ECTS)[17]. Тогда же было объявлено, что в отличие от
                        Warcraft
                        II
                        новая
                        игра будет полностью трёхмерной, в ней будет шесть игровых рас (Орки, Люди, Демоны и ещё три
                        неизвестных), и
                        она
                        будет выполнена в новом жанре Role Playing Strategy[18][19][20]. Последнее означало, что игрок
                        будет
                        меньше
                        фокусироваться на сборке ресурсов и управлении базой и больше — на развитии подконтрольных ему
                        отрядов и
                        выполнением квестов. Были показаны скриншоты игры и видеоролики, демонстрирующие геймплей.
                        Графически
                        игра
                        выглядела весьма хорошо для того времени. Было сообщено, что игра выйдет в 2000 году[21].

                        К 2000 году стало известно, что четвёртой игровой расой станет Нежить[22]. В июне этого же года
                        журнал
                        GameSpot
                        провел интервью с Робом Пардо, который сообщил, что игра закончена на 30 % и что из игры была
                        удалена
                        одна
                        из
                        шести рас, которая так и осталась неназванной[23][24]. В декабре стала известна пятая
                        играбельная
                        раса,
                        ею
                        стала
                        раса Ночных эльфов[25].

                        На выставке MacWorld Expo в июле 2000 года Blizzard объявила, что игра будет выпущена и для
                        компьютеров
                        Macintosh[26].

                        В конце 2000 года игра была перенесена на начало 2001 года. Тогда же Blizzard отказалась от
                        жанра
                        RPS, и
                        было
                        решено оставить игру в стиле Real Time Strategy с наличием героев. Позже сроки выхода сдвигались
                        ещё
                        два
                        раза:
                        сначала игру перенесли на вторую половину 2001 года[27], и затем — окончательно на 2002 год[28].

                        1 февраля 2001 года стало известно полное название игры — Warcraft III: Reign of Chaos. Тогда же
                        стало
                        известно,
                        что количество играбельных рас сократится до четырёх. Ими стали Альянс, Орда, Ночные эльфы и
                        Нежить.
                        Из
                        Пылающего легиона решили оставить только юнитов и здания[29].

                        В ноябре 2001 года Blizzard выпустила обновление 1.09c для Diablo II, с помощью которого
                        производился
                        анонимный
                        сбор информации о конфигурациях компьютеров для будущей оптимизации Warcraft III. Однако, при
                        установке
                        обновления можно было отменить сбор данных[30].

                        С 7 января по 8 февраля 2002 года состоялся набор бета-тестеров. Было отобрано около 5000
                        человек[31][32]. В
                        бета-версии было возможно играть только через Battle.net, и отсутствовали одиночная игра и
                        возможность
                        игры
                        по
                        локальной сети. Для тех, кто не участвовал в бета-тесте, Blizzard примерно раз в 1-4 дня
                        представляла
                        одного
                        юнита или героя из игры.

                        Существует английская демоверсия игры, которая вышла 2 декабря 2002 года, через шесть месяцев
                        после
                        выхода
                        игры[33]. Она содержит 5 миссий за орду, две из которых взяты из пролога Reign of Chaos, а три
                        новые
                        в
                        дальнейшем вошли как отдельная мини-кампания в дополнение The Frozen Throne. В демоверсии нет
                        возможности
                        играть
                        по сети и на пользовательских картах, и отсутствует редактор World Editor. В ней также можно
                        играть
                        через
                        Battle.net, но только матч один-на-один за орду и только между игроками демоверсии. Она занимает
                        около
                        100
                        Мб, и
                        её PC- и Mac-версии можно скачать с ftp Blizzard. Из всех юнитов только Тралл говорит смешные
                        фразы,
                        если по
                        нему кликать несколько раз. Остальные юниты смешных фраз не говорят.
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

warcraft/templates/warcraft/gallery_page.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="container mt-5 pt-5">
        <div class="row">
            <div class="col-md-12 text-center">
                <h1 class="display-4">Галерея фотографий об игре</h1>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-md-4">
                <a href="{% static 'images/img1.jpg' %}" data-lightbox="game-gallery" data-title="Описание фото 1">
                    <img src="{% static 'images/img1.jpg' %}" alt="Фото 1" class="img-fluid rounded">
                </a>
            </div>
            <div class="col-md-4">
                <a href="{% static 'images/img2.jpg' %}" data-lightbox="game-gallery" data-title="Описание фото 2">
                    <img src="{% static 'images/img2.jpg' %}" alt="Фото 2" class="img-fluid rounded">
                </a>
            </div>
            <div class="col-md-4">
                <a href="{% static 'images/img2.jpg' %}" data-lightbox="game-gallery" data-title="Описание фото 3">
                    <img src="{% static 'images/img2.jpg' %}" alt="Фото 3" class="img-fluid rounded">
                </a>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-md-4">
                <a href="{% static 'images/img1.jpg' %}" data-lightbox="game-gallery" data-title="Описание фото 1">
                    <img src="{% static 'images/img1.jpg' %}" alt="Фото 1" class="img-fluid rounded">
                </a>
            </div>
            <div class="col-md-4">
                <a href="{% static 'images/img2.jpg' %}" data-lightbox="game-gallery" data-title="Описание фото 2">
                    <img src="{% static 'images/img2.jpg' %}" alt="Фото 2" class="img-fluid rounded">
                </a>
            </div>
            <div class="col-md-4">
                <a href="{% static 'images/img2.jpg' %}" data-lightbox="game-gallery" data-title="Описание фото 3">
                    <img src="{% static 'images/img2.jpg' %}" alt="Фото 3" class="img-fluid rounded">
                </a>
            </div>
        </div>
    </div>
{% endblock %}

warcraft/templates/warcraft/start_page.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <img class="banner" src="{% static 'images/banner.jpeg' %}" alt="Warcraft 3 Banner">
{% endblock %}

warcraft/templates/warcraft/video_page.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="container mt-5 pt-5">
        <div class="row">
            <div class="col-md-12 text-center">
                <h1 class="display-4">Видео об игре</h1>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-md-6 offset-md-3">
                <video controls class="img-fluid">
                    <source src="{% static '' %}" type="video/mp4">
                    Ваш браузер не поддерживает видео.
                </video>
            </div>
        </div>
    </div>
{% endblock %}